spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tQP2K7uQMEHvCB5StyF
      secret-key: G4eoWmOywewCnEOJlxzVgdMWRh6flr
      oss:
        endpoint: oss-cn-guangzhou.aliyuncs.com
        bucket: mall-myproduct

  application:
    name: mall-third-party
